from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('cuenta/', views.admin_index, name='admin_index'),
    path('cuenta/cambiar-password/', views.cuenta_cambiar_password, name='cuenta_cambiar_password'),
    path('cuenta/cambiar-password-vendedor/', views.admin_cambiar_password_vendedor, name='admin_cambiar_password_vendedor'),
    path('cuenta/usuarios/', views.admin_usuarios_index, name='admin_usuarios_index'),
    path('cuenta/usuarios/crear/', views.admin_usuarios_crear, name='admin_usuarios_crear'),
    path('cuenta/usuarios/<int:pk>/eliminar/', views.admin_usuarios_eliminar, name='admin_usuarios_eliminar'),
    path('', views.index, name='index'),
    path('pos/', views.pos_view, name='pos'),
    path('pos/procesar-pago/', views.pos_procesar_pago, name='pos_procesar_pago'),
    path('pos/buscar-clientes/', views.pos_buscar_clientes, name='pos_buscar_clientes'),
    path('pos/crear-cliente/', views.pos_crear_cliente, name='pos_crear_cliente'),
    path('productos/', views.producto_index, name='producto_index'),
    path('productos/crear/', views.producto_crear, name='producto_crear'),
    path('productos/<int:pk>/editar/', views.producto_editar, name='producto_editar'),
    path('productos/<int:pk>/eliminar/', views.producto_eliminar, name='producto_eliminar'),
    path('categorias/', views.categoria_index, name='categoria_index'),
    path('categorias/crear/', views.categoria_crear, name='categoria_crear'),
    path('categorias/<int:pk>/editar/', views.categoria_editar, name='categoria_editar'),
    path('categorias/<int:pk>/eliminar/', views.categoria_eliminar, name='categoria_eliminar'),
    path('metodos-pago/', views.metodopago_index, name='metodopago_index'),
    path('metodos-pago/crear/', views.metodopago_crear, name='metodopago_crear'),
    path('metodos-pago/<int:pk>/editar/', views.metodopago_editar, name='metodopago_editar'),
    path('metodos-pago/<int:pk>/eliminar/', views.metodopago_eliminar, name='metodopago_eliminar'),
    path('clientes/', views.cliente_index, name='cliente_index'),
    path('clientes/<int:pk>/editar/', views.cliente_editar, name='cliente_editar'),
    path('clientes/<int:pk>/eliminar/', views.cliente_eliminar, name='cliente_eliminar'),
    path('ventas/', views.venta_index, name='venta_index'),
    path('ventas/<int:pk>/', views.venta_detail, name='venta_detail'),
    path('ventas/<int:venta_pk>/pago/<int:pago_pk>/validar/', views.pago_validar, name='pago_validar'),
    path('cierre-caja/', views.cierre_caja_index, name='cierre_caja_index'),
    path('cierre-caja/nuevo/', views.cierre_caja_nuevo, name='cierre_caja_nuevo'),
    path('cierre-caja/<int:pk>/', views.cierre_caja_detail, name='cierre_caja_detail'),
    path('reportes/', views.reportes_index, name='reportes_index'),
    path('promociones/', views.promocion_index, name='promocion_index'),
    path('promociones/crear/', views.promocion_crear, name='promocion_crear'),
    path('promociones/<int:pk>/editar/', views.promocion_editar, name='promocion_editar'),
    path('promociones/<int:pk>/eliminar/', views.promocion_eliminar, name='promocion_eliminar'),
]

